# fly.toml app configuration file generated for cartly on 2024-12-05T20:39:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cartly'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[deploy]
release_command = './bin/rails db:migrate'

[env]
RACK_ENV = 'production'
RAILS_ENV = 'production'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-8x'

[[mounts]]
source = "translations"
destination = "/rails/config/locale"

[[statics]]
guest_path = '/rails/public'
url_prefix = '/'
